
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ALI HAIDER
 */
public class doctors_reports_panel extends javax.swing.JPanel {

    /**
     * Creates new form doctors_reports_panel
     */
    Connection con;

    public doctors_reports_panel() {
        initComponents();
        AutoCompleteDecorator.decorate(t7);

        con = databaseconnetion.get_Connection();

    }

    /**
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refresher_of_doc_panel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        t7 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        refresher_of_doc_panel.setText("jButton3");
        refresher_of_doc_panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresher_of_doc_panelActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(226, 226, 226));
        setPreferredSize(new java.awt.Dimension(476, 350));

        jPanel1.setBackground(new java.awt.Color(243, 243, 243));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel3.setText("Doctors Statistics Reports");

        t7.setBackground(new java.awt.Color(19, 80, 161));
        t7.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        t7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Reference" }));
        t7.setBorder(null);

        jButton1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gsp.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alldocs.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(t7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(144, 144, 144))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(63, 63, 63)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void send_parameters() {

        String doctors_name = t7.getSelectedItem().toString();

        int reports_count = 0;
        int total_tests = 0;
        double total_sum_without_discount = 0.0;
        double total_discounts = 0.0;
        double total_sum_with_discount = 0.0;
        double total_payed = 0.0;
        double change = 0.0;
        double reamining = 0.0;
        double total_earning = 0.0;

        try {
            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery("SELECT * FROM  patients_reports WHERE Referred_By ='" + doctors_name + "' ");

            while (rs.next()) {
                reports_count++;

                total_tests += Integer.parseInt(rs.getString(11));
                total_sum_without_discount += Double.parseDouble(rs.getString(12));
                total_sum_with_discount += Double.parseDouble(rs.getString(14));
                total_discounts += Double.parseDouble(rs.getString(13));
                total_payed += Double.parseDouble(rs.getString(15));
                total_earning += Double.parseDouble(rs.getString(14));
                change += Double.parseDouble(rs.getString(16));
                reamining += Double.parseDouble(rs.getString(17));
            }

            String lab_name = login_frame.jLabel1.getText();

            HashMap parameter = new HashMap();
            parameter.put("reference_dr_name_for_counter", doctors_name);
            parameter.put("tr", reports_count);
            parameter.put("tt", total_tests);
            parameter.put("ta", total_sum_without_discount);
            parameter.put("gt", total_sum_with_discount);
            parameter.put("d", total_discounts);
            parameter.put("pa", total_payed);
            parameter.put("income", total_earning);
            parameter.put("cr", change);
            parameter.put("r", reamining);

            parameter.put("lab_name", lab_name);

            try {
                Report_View vr = new Report_View("src\\Reports\\tests_counter_of_doctors_report.jasper", parameter);
                vr.setVisible(true);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "          Exception Catched     " + ex + "     ", "Doctors Reports", JOptionPane.ERROR_MESSAGE);

            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "        Exception    !              " + ex + "               ", "Doctors Reports", JOptionPane.INFORMATION_MESSAGE);

        }

    }

    public void load_cat_box_of_docs() {

        t7.removeAllItems();

        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT Distinct Doctor_Name FROM  reference_doctors");
            t7.addItem("Self");
            t7.addItem("OPD");

            while (rs.next()) {
                String element = rs.getString(1);
                t7.addItem(element);
            }

        } catch (SQLException ex) {
            Logger.getLogger(tests_panel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        send_parameters();

        t7.setSelectedIndex(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String lab_name = login_frame.jLabel1.getText();
        HashMap parameter = new HashMap();
        parameter.put("lab_name", lab_name);
        try {
            Report_View vr = new Report_View("src\\Reports\\reference_doctors_report.jasper", parameter);
            vr.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "          Exception Catched     " + ex + "     ", "Doctors Reports", JOptionPane.ERROR_MESSAGE);

        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void refresher_of_doc_panelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresher_of_doc_panelActionPerformed
        load_cat_box_of_docs();    // TODO add your handling code here:
    }//GEN-LAST:event_refresher_of_doc_panelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JButton refresher_of_doc_panel;
    private javax.swing.JComboBox<String> t7;
    // End of variables declaration//GEN-END:variables
}
