/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ALI HAIDER
 */
import com.sun.prism.paint.Color;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;

public class Report_View extends javax.swing.JFrame {

    /**
     * Creates new form Report_View
     */
    public Report_View(String fileName) {

        this(fileName, null);

    }

    public Report_View(String fileName, HashMap para) {

        Image icon = Toolkit.getDefaultToolkit().getImage("src\\images\\frameicon.png");
        this.setIconImage(icon);
        setTitle("Clinical Lab Solutions (Reports)");
        JPanel p = new JPanel();
        p.setBackground(java.awt.Color.WHITE);
        p.setLayout(new BorderLayout());

        this.add(p);
        Connection con = null;

        con = databaseconnetion.get_Connection();

        try {
            JasperPrint print = JasperFillManager.fillReport(fileName, para, con);
            JRViewer viewer = new JRViewer(print);

            viewer.setBackground(java.awt.Color.WHITE);
            viewer.setForeground(java.awt.Color.yellow);
            Container c = getContentPane();
            p.add(viewer, BorderLayout.CENTER);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "    Exception in Report View                 " + ex + "            ", "Reports View", JOptionPane.ERROR_MESSAGE);
        }

        setBounds(200, 40, 1000, 800);
        this.setBackground(java.awt.Color.white);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    private Report_View() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void print() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pathalogy Lab Software (Reports)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

