
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashMap;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ALI HAIDER
 */
public class sales_report_buttons extends javax.swing.JPanel {

    /**
     * Creates new form sales_report_buttons
     */
    Connection con;

    public sales_report_buttons() {
        initComponents();
        fromdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calender.png")));
        todate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calender.png")));

        con = databaseconnetion.get_Connection();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fromdate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        todate = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 243, 243));

        jPanel1.setBackground(new java.awt.Color(243, 243, 243));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel3.setText("Statistics Reports");

        fromdate.setBackground(new java.awt.Color(243, 243, 243));
        fromdate.setToolTipText("");
        fromdate.setDateFormatString("yyyy-MM-dd");
        fromdate.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        fromdate.setIcon(null);

        jButton1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate reprot.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate reprot.png"))); // NOI18N
        jButton2.setToolTipText("Generate reports Betwee Given Dates");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel2.setText("Select End Date");

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel1.setText("Select Starts Date  ");

        todate.setBackground(new java.awt.Color(243, 243, 243));
        todate.setToolTipText("");
        todate.setDateFormatString("yyyy-MM-dd");
        todate.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        todate.setIcon(null);

        jButton3.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/todayreport.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(todate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fromdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jButton1)
                        .addComponent(jButton3)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromdate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(todate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
 public void send_parameters_whole() {

        int reports_count = 0;
        int total_tests = 0;
        double total_sum_without_discount = 0.0;
        double total_discounts = 0.0;
        double total_sum_with_discount = 0.0;
        double total_payed = 0.0;
        double change = 0.0;
        double reamining = 0.0;
        double total_earning = 0.0;

        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM  patients_reports ");
            while (rs.next()) {
                reports_count++;
                total_tests += Integer.parseInt(rs.getString(11));
                total_sum_without_discount += Double.parseDouble(rs.getString(12));
                total_sum_with_discount += Double.parseDouble(rs.getString(14));
                total_discounts += Double.parseDouble(rs.getString(13));
                total_payed += Double.parseDouble(rs.getString(15));
                total_earning += Double.parseDouble(rs.getString(14));
                change += Double.parseDouble(rs.getString(16));
                reamining += Double.parseDouble(rs.getString(17));
            }

            HashMap parameter = new HashMap();
            String lab_name = login_frame.jLabel1.getText();
            parameter.put("lab_name", lab_name);
            parameter.put("total_reports", reports_count);
            parameter.put("total_tests", total_tests);
            parameter.put("total_amount", total_sum_without_discount);
            parameter.put("grand_total", total_sum_with_discount);
            parameter.put("discount", total_discounts);
            parameter.put("payed_amount", total_payed);
            parameter.put("income", total_earning);
            parameter.put("chnage_returned", change);
            parameter.put("reaminings", reamining);

            try {
                Report_View vr = new Report_View("src\\Reports\\whole_patients_sales_report.jasper", parameter);
                vr.setVisible(true);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "          Exception Catched          ", "Statistics Report", JOptionPane.ERROR_MESSAGE);

            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "        Please Select proper Dates    !                     ", "Statistics Report", JOptionPane.INFORMATION_MESSAGE);

        }

    }

    public void send_parameters(String fdate, String tdate) {

        int reports_count = 0;
        int total_tests = 0;
        double total_sum_without_discount = 0.0;
        double total_discounts = 0.0;
        double total_sum_with_discount = 0.0;
        double total_payed = 0.0;
        double change = 0.0;
        double reamining = 0.0;
        double total_earning = 0.0;

        try {
            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery("SELECT * FROM  patients_reports WHERE Reporting_Date BETWEEN  '" + fdate + "' AND '" + tdate + "' ");
            while (rs.next()) {
                reports_count++;
                total_tests += Integer.parseInt(rs.getString(11));
                total_sum_without_discount += Double.parseDouble(rs.getString(12));
                total_sum_with_discount += Double.parseDouble(rs.getString(14));
                total_discounts += Double.parseDouble(rs.getString(13));
                total_payed += Double.parseDouble(rs.getString(15));
                total_earning += Double.parseDouble(rs.getString(14));
                change += Double.parseDouble(rs.getString(16));
                reamining += Double.parseDouble(rs.getString(17));
            }

            HashMap parameter = new HashMap();
            String lab_name = login_frame.jLabel1.getText();
            parameter.put("lab_name", lab_name);
            parameter.put("from_date", fdate);
            parameter.put("to_date", tdate);
            parameter.put("total_reports", reports_count);
            parameter.put("total_tests", total_tests);
            parameter.put("total_amount", total_sum_without_discount);
            parameter.put("grand_total", total_sum_with_discount);
            parameter.put("discount", total_discounts);
            parameter.put("payed_amount", total_payed);
            parameter.put("income", total_earning);
            parameter.put("chnage_returned", change);
            parameter.put("reaminings", reamining);

            try {
                Report_View vr = new Report_View("src\\Reports\\patients_reports_by_dates.jasper", parameter);
                vr.setVisible(true);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "          Exception Catched          ", "Statistics Report", JOptionPane.ERROR_MESSAGE);

            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "        Please Select proper Dates    !                     ", "Statistics Report", JOptionPane.INFORMATION_MESSAGE);

        }

    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            if (fromdate.getDate().toString().equals("") || todate.getDate().toString().equals("")) {
                JOptionPane.showMessageDialog(null, "        Please Select proper Dates    !                     ", "Statistics Report", JOptionPane.INFORMATION_MESSAGE);
                String date = "";

            } else {
                SimpleDateFormat df1 = new SimpleDateFormat("yyyy-MM-dd");
                String fdate = df1.format(fromdate.getDate());

                SimpleDateFormat df2 = new SimpleDateFormat("yyyy-MM-dd");
                String tdate = df2.format(todate.getDate());

                send_parameters(fdate, tdate);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "        Please Select proper Dates    !                     ", "Statistics Report", JOptionPane.INFORMATION_MESSAGE);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        send_parameters_whole();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        send_parameters(java.time.LocalDate.now().toString(), java.time.LocalDate.now().toString());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fromdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser todate;
    // End of variables declaration//GEN-END:variables
}
