
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ALI HAIDER
 */
public class Tests_reports_panel extends javax.swing.JPanel {

    /**
     * Creates new form Tests_reports_panel
     */
    Connection con;

    public Tests_reports_panel() {
        initComponents();
        AutoCompleteDecorator.decorate(category_Box);

        con = databaseconnetion.get_Connection();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        load_teste_cat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        category_Box = new javax.swing.JComboBox<>();

        load_teste_cat.setText("jButton1");
        load_teste_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load_teste_catActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(243, 243, 243));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel3.setText("Categories/Tests Reports");

        jButton2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CR.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/select etstsreprot.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/allatests.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        category_Box.setBackground(new java.awt.Color(19, 64, 161));
        category_Box.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        category_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category" }));
        category_Box.setBorder(null);
        category_Box.setOpaque(false);
        category_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_BoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(category_Box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(category_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
public void load_cat_box() {

        category_Box.removeAllItems();
        category_Box.addItem("Select Category");
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT DISTINCT Category_Code  FROM  tests_catagories");

            while (rs.next()) {
                String element = rs.getString(1);
                category_Box.addItem(element);
            }

        } catch (SQLException ex) {
            Logger.getLogger(tests_panel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String lab_name = login_frame.jLabel1.getText();
        HashMap parameter = new HashMap();
        parameter.put("lab_name", lab_name);

        try {
            Report_View vr = new Report_View("src\\Reports\\category_report.jasper", parameter);
            vr.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "          Exception Catched     " + ex + "     ", "Tests Statistical Reports", JOptionPane.ERROR_MESSAGE);

        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    public void send_parameters() {
        String category_name = category_Box.getSelectedItem().toString();
        String lab_name = login_frame.jLabel1.getText();
        HashMap parameter = new HashMap();
        parameter.put("test_category_for_jasper_report", category_name);
        parameter.put("lab_name", lab_name);

        try {
            Report_View vr = new Report_View("src\\Reports\\Tests_report_By_Category.jasper", parameter);
            vr.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "          Exception Catched     " + ex + "     ", "Pathology Lab Software", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (category_Box.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "               Kindly Select Any Category To View Tests    !           ", "Pathology Lab Sofwtare", JOptionPane.ERROR_MESSAGE);
            category_Box.grabFocus();
        } else

            send_parameters();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String lab_name = login_frame.jLabel1.getText();
        HashMap parameter = new HashMap();
        parameter.put("lab_name", lab_name);

        try {
            Report_View vr = new Report_View("src\\Reports\\tests_whole_report.jasper", parameter);
            vr.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "          Exception Catched     " + ex + "     ", "Pathology Lab Software", JOptionPane.ERROR_MESSAGE);

        }      // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void load_teste_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load_teste_catActionPerformed
        load_cat_box(); // TODO add your handling code here:
    }//GEN-LAST:event_load_teste_catActionPerformed

    private void category_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_category_BoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> category_Box;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JButton load_teste_cat;
    // End of variables declaration//GEN-END:variables
}

